# This is a basic workflow to help you get started with Actions

name: Chrome UI Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  chrome-ui-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: List files project
        run: ls -l
